### ISSUE TITLE
Please update into the future

### ISSUE THREAD

**Issue by MrKiller01** [md5sha256/AreaShop#10]
#### Current behavior
The plugin does not start in MC 1.18.2

#### New behavior
That the plugin works under 1.18.2

#### Steps to reproduce (for bugs)

1. Not a bug
2. Fails to start during server restart under Paper
3. 
4. 

#### Your environment (for bugs)

* Server platform (Bukkit, Spigot, etc.): Paper
* Server version: [13:17:55 INFO]: This server is running Paper version git-Paper-258 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 8897cea)
You are running the latest version
Previous version: git-Paper-241 (MC: 1.18.2)
* AreaShop version: Version: 2.7.5-SNAPSHOT
[13:16:52 INFO]: - Author(s): NLThijs48
[13:16:52 INFO]: - Status: Disabled
* WorldEdit version: - Version: 7.2.10-SNAPSHOT+6120-f50a81f
* WorldGuard version: - Version: 7.0.6+1cff55f
* Vault version: - Version: 1.7.3-b131

#### Your config files (for bugs)

[config.zip](https://github.com/md5sha256/AreaShop/files/8285363/config.zip)

**Comment by md5sha256** [comment]
Fixed with 2.7.6
