### ISSUE TITLE
unrented event not returning placeholders

### ISSUE THREAD

**Issue by Namor0001** [md5sha256/AreaShop#11]
**Current behavior**

When I unrent an area, the placeholders (player/uuid) set in the event for unrented return the text < UNKOWN>
NOTE: I have had to add a space in front of the Text UNKOWN 

**Expected behavior**

it would work like the Rented Event or Extended event.

if I have the command line
"Say Hi %player%"
server message would be 
Hi 1Namor

**Steps to reproduce**

1. edit the default.yml lines
unrented:
      before:
      after:
         - "say Hi %player%"
2. In game unrent the area 

server message will be 

"Hi < UNKOWN>" 

The Rent and Extended events will both return
"Hi Namor"

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Paper
* Server version: 386
* AreaShop version:  2.7.7 (bug also exists in 2.76)
* WorldEdit version: 7.2.10
* WorldGuard version: 7.0.6
* Vault version: 1.7.3--b131

**Your config files**

[Config.zip](https://github.com/md5sha256/AreaShop/files/8954241/Config.zip)

**Comment by md5sha256** [comment]
Fixed in #13
