### ISSUE TITLE
Small question regarding the plugin 

### ISSUE THREAD

**Issue by TuckerAndrews3** [md5sha256/AreaShop#14]
I hate to leave this as an issue but I couldn't find a way to contact the developers.

Let's say I have a large world guard region over a city, and I want a small building in the city to be rentable. I set a region inside the bigger region of the city around the small building, and I make that rentable. Will the player who rents it still be able to build inside that small region despite the rules of the larger region?

**Comment by md5sha256** [comment]
The rules should be the same as WorldGuard. In theory, if you do the same setup without AreaShop you should be able to figure out whether that player can build inside the small region. AreaShop will respect the rules of the WorldGuard region.
