### ISSUE TITLE
Server is crashing while adding offline players to a region

### ISSUE THREAD

**Issue by Plattio** [md5sha256/AreaShop#15]
**Current behavior**

We have like 300 regions with AreaShop implemented and if i add a offline player to my region, the server is lagging. Same if i set a offline player as owner for a shop.

Crash log: https://pastebin.com/raw/1wHHaPMy

**Expected behavior**

Server is not lagging

**Steps to reproduce**

- /as addfriend (Offline Player)
- /as setowner (Offline Player)

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Paper
* Server version: MC 1.19 (git-Paper-81)
* AreaShop version: 2.7.8
* WorldEdit version: 7.2.11
* WorldGuard version: 7.0.8
* Vault version: 1.7.3

**Your config files**

https://workupload.com/file/r2WDMA3Pk8w (for security reasons only 1 download possible)

**Comment by md5sha256** [comment]
This crash is due to a sync lookup for an offline player. I'll have a look into this.

**Comment by md5sha256** [comment]
Fixed in 2.7.9, thanks for reporting
