### ISSUE TITLE
chat formatting bugs.

### ISSUE THREAD

**Issue by Zoltus** [md5sha256/AreaShop#16]
chatPrefix:
  - '&f&lMoti&a&lMaa'
 Will bee **Moti**Maa ingame. The second part wont be bold

**Comment by md5sha256** [comment]
could you give more context?

**Comment by Zoltus** [comment]
Having '&f&lMoti&a&lMaa' in config as prefix will be ingame:
![2023-03-02_10-32-44](https://user-images.githubusercontent.com/23402980/222374353-1488067b-4229-44e2-be50-324bc0066a55.png)

The second part wont be bold for somereason.

**Comment by Zoltus** [comment]
any news?

**Comment by alemicrorez** [comment]
I don't have the definitive solution but you can try putting the "&r" at the end of the color word so that the new color word is fine
"&f&lMoti&r&a&lMaa"

**Comment by Zoltus** [comment]
Probably could work but i dont have need for this anymore so im closing this.
