### ISSUE TITLE
Bug with the oak_signs

### ISSUE THREAD

**Issue by alemicrorez** [md5sha256/AreaShop#18]
**Current behavior**

When configuring a sign with /as addsign <name> or sign ( [asbuy] ...) it is configured correctly and the commands work but when the server is restarted the signs stop working, I have noticed that only those for sale, the signs for rent work well and are not deconfigured
No error occurs

**Expected behavior**

don't misconfigure the signs jaja

**Steps to reproduce**

1. set the dungeon region with worldguard
2. I put up a sign and place to sell ([asbuy])
3. I see that it was configured correctly buying and selling the region
4. I restart the server
5. the sign magically deconfigures and no longer lets me buy the region

**Your environment**

* Server platform (Bukkit, Spigot, etc.):  Paper
* Server version: git-Paper-545 (MC: 1.19.4) 
* AreaShop version:  2.7.12
* WorldEdit version: 7.2.14+6360-094b734
* WorldGuard version: 7.0.8+33cdb4a
* Vault version: 1.7.3-b131

**Your config files**

[archive-2023-06-22T022223-0400.zip](https://github.com/md5sha256/AreaShop/files/11829546/archive-2023-06-22T022223-0400.zip)

**Comment by md5sha256** [comment]
This issue was encountered when the way signs were stored was refactored a few versions back. I'll have a look into this

**Comment by md5sha256** [comment]
fixed in 2.7.13
