### ISSUE TITLE
Bug with the signs

### ISSUE THREAD

**Issue by Sandukhan** [md5sha256/AreaShop#20]
**Current behavior**
Somebody already reported this bug a while back, but its still seems to be persistent in the new version (2.7.13). 
After server restart, areashop 'looses' all assigned region signs. 

Also areashop send warnings while server shutdown for regions not having a owner, but that seems to be a diffrent issue.

**Steps to reproduce**
1. Create a region in WG
2. Register the region in areashop as [buy]
3. Save and restart the server.

**Your environment**
* Paper 1.20.1-169
* Java 17
* AreaShop-2.7.13
* WorldEdit 7.2.15  
* WorldGuard 7.0.9
* Vault 1.7.3-b131

**Your config files**
- used the default setup, no config changes

**Comment by md5sha256** [comment]
AreaShop cannot save the region properly if there is no owner, that warning was added so at least it doesnt fail totally silently. I'm mot sure why this is happening but at least we know what it is now

**Comment by doc1707** [comment]
Hi, I am having exactly the same issue with signs...

They get lost every time the server is restarted.

Has any solution been found to this?

**Comment by doc1707** [comment]
> AreaShop cannot save the region properly if there is no owner, that warning was added so at least it doesnt fail totally silently. I'm mot sure why this is happening but at least we know what it is now

Another observation regarding the sign bug, is that it only persists in "buy" regions, "rental" regions seem to be fine and the signs are saved on reload

**Comment by md5sha256** [comment]
Interesting, let me dig into the buy impl

**Comment by md5sha256** [comment]
Just to confirm, the sign blocks stay but they no longer function as interactive AS signs?

**Comment by doc1707** [comment]
> Just to confirm, the sign blocks stay but they no longer function as interactive AS signs?

So, let me try to describe it to you, to the best of my ability, as a non-technical person. I have been running your forks on my serv for almost a year now, and I've only recently updated (about a week ago) from 1.16.5 to 1.20.1. That is when this problem started to appear. So on 1.16.5 it has been running fine and sign functioned well after server reloads. So it might be to the way signs are handled in 1.20.X. After the update to mc purpur 1.20.1 and an update to your latest released snapshot, the problem appeared as described further. So I have "buy" regions and I have "rent" regions. Rent regions are working fine and signs save their functionality after server reloads. However, "buy" regions are working as following, you have region A with 2 signs assigned to it, sign 1 and sign 2, the signs are at different location, but are linked to one region. After server restart, but signs STOP being interactive adn just function as a normal "editable" sign (another annoying feature), so BOTH sign 1 and sign 2 assigned to region A, are stopping functioning as interactive. Yet they are both saved in region files and every "buy" region still has two signs assigned to them, yet they are not interactive. HOWEVER, when you go to either ONE sign (so 1 or 2) and UPDATE it, with /as addsign A (region A), a second sign also seems yo update and starts functioning fine. So if after server restart, both signs stop functioning, but you go and update sign 1, sign 2 starts working fine as well. And all of this gets reset again after server restart. So this is, to the best of my ability, how I can describe it to you. 

Hope this might be helpfull to you mate! Thank you VERY MUCH for your efforts in keeping this plugin afloat, this is very much appreciated by me and thousands of my players! Hope you can find a resolution to this!

**Comment by doc1707** [comment]
Is there any foreseeable resolution to this?

**Comment by seema84** [comment]
> Just to confirm, the sign blocks stay but they no longer function as interactive AS signs?

I can confirm exactly that

**Comment by seema84** [comment]
@md5sha256 Do you have an approximate time frame for fixing the problem?

**Comment by doc1707** [comment]
@md5sha256 Sir, we are all so much relying on you with this plugin. Thank you once again for keeping it afloat all of this time! Can you please try and fix the sign issue?

**Comment by md5sha256** [comment]
No time frame, but I'll start looking at it today

**Comment by seema84** [comment]
> [14:32:37] [Server thread/INFO]: [AreaShop] Enabling AreaShop v2.7.14
> [14:32:37] [Server thread/WARN]: java.lang.ClassNotFoundException: me.wiefferink.areashop.adapters.platform.v1_20_R1.NMSImpl
> [14:32:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183)
> [14:32:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150)
> [14:32:37] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> [14:32:37] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
> [14:32:37] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
> [14:32:37] [Server thread/WARN]: 	at AreaShop-2.7.14.jar//me.wiefferink.areashop.AreaShop.onEnable(AreaShop.java:179)
> [14:32:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
> [14:32:37] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
> [14:32:37] [Server thread/WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
> [14:32:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
> [14:32:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642)
> [14:32:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553)
> [14:32:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635)
> [14:32:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434)
> [14:32:37] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
> [14:32:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1100)
> [14:32:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317)
> [14:32:37] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
> [14:32:37] [Server thread/ERROR]: [AreaShop] Failed to initialize NMS implementation!
> [14:32:37] [Server thread/ERROR]: [AreaShop] The plugin has not started, fix the errors listed above

dont work with 1.20.1 (which is still the most used version)

**Comment by md5sha256** [comment]
Update to 1.20.2. 1.20.2 is at 31.7% compared to 36.7% of 1.20.1, i don't see a reason to explicitly support 1.20.1 anymore but I'll change it so future versions don't outright fail when the adapter isn't found

**Comment by doc1707** [comment]
> Update to 1.20.2. 1.20.2 is at 31.7% compared to 36.7% of 1.20.1, i don't see a reason to explicitly support 1.20.1 anymore but I'll change it so future versions don't outright fail when the adapter isn't found

Hi Dev! So are you going to reinstate the 1.20.1 compatibility?

**Comment by md5sha256** [comment]
Not right now, but some point in the future maybe

**Comment by md5sha256** [comment]
See 2.7.15-SNAPSHOT, this should stop the plugin from crashing on 1.20 and 1.20.1

**Comment by doc1707** [comment]
Thank you for a quick turnaround!

**Comment by seema84** [comment]
> See 2.7.15-SNAPSHOT, this should stop the plugin from crashing on 1.20 and 1.20.1

thanks
