### ISSUE TITLE
Minecraft sign edit overrides right click of a sign

### ISSUE THREAD

**Issue by RobZenFL** [md5sha256/AreaShop#29]
**Current behavior**
When a player right clicks an areashop sign, the sign opens, since minecraft added the signedit directly into minecraft. This only happens, when an area is not owned. So if I own a region I can still right click the sign and e.g. expand the rent. I tried to disable signedit via script or plugin, but then still areashop doesn't recognize the click of the player.
Shift + rightclick still works fine, so I assume the signedit feature interrupts the functionality of areashop.

**Expected behavior**
Areashop should recognize the clicked sign and override the signedit function of minecraft.

**Steps to reproduce**
1. Set a region, create an AS-region and link a sign
2. Right click the sign
3. The sign opens and you can edit the content
4. No action of areashop is triggered, so the region can't be rented or bought.

**Your environment**
* Server platform (Bukkit, Spigot, etc.): Paper
* Server version: git-Paper-447 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 0052e2d)
* AreaShop version: 2.7.17
* WorldEdit version: FAWE 2.9.1;84f661d
* WorldGuard version: 7.0.9+5934e49
* Vault version: 1.7.3-b131

**Your config files**
https://www.dropbox.com/scl/fi/4061jnahzq6p8jvv6dbw3/PluginConfigs.zip?rlkey=9m5tih4kb9f01zu5rcudr6a0t&dl=0

**Comment by md5sha256** [comment]
Planning on fixing this for 2.9.x targeting 1.20.6 and 1.21.

**Comment by md5sha256** [comment]
Cannot reproduce, try with 2.9.0 or 2.9.1 (non-snapshot versions)
