### ISSUE TITLE
Area sign does't work on right click!

### ISSUE THREAD

**Issue by Xirren** [md5sha256/AreaShop#32]
**Current behavior**
Area sign does NOT work on right click!

**Expected behavior**
Right clicking an Area Sign should rent/buy this area.

**Steps to reproduce**

1. Create an area to be rent/buy
2. Create an area sign
3. Right click the sign
4. Nothing happens

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Paper
* Server version: 1.21-110-master
* AreaShop version: 2.9.1
* WorldEdit version: FAWE 2.11.1 SNAPSHOT-859
* WorldGuard version: 7.0.11 beta1
* Vault version: 1.7.3

**Your config files**

**Comment by md5sha256** [comment]
See: https://github.com/md5sha256/AreaShop/issues/30#issuecomment-2246814722
