### ISSUE TITLE
Command alias doesn't work.

### ISSUE THREAD

**Issue by kamil445** [md5sha256/AreaShop#33]
**Current behavior**
Aliases doesn't work, massage in console: 
[19:30:59] [Server thread/WARN]: Could not register alias dzialka because it contains commands that do not exist: areashop find buy

**Expected behavior**
Aliases should work.

**Steps to reproduce**

1. Create alias in commands.yml,
my commands.yml:
  dzialka:
  - areashop find buy

3. Try to use alias in game

**Your environment**

* Server platform (Bukkit, Spigot, etc.): Purpur
* Server version: 1.21
* AreaShop version: 2.9.1
* WorldEdit version: 7.3.8
* WorldGuard version: 7.0.12
* Vault version: 1.5.6-b49

**Your config files**

**Comment by md5sha256** [comment]
I'm not sure if this is an AreaShop specific issue. Are you able to create aliases for other commands?

**Comment by md5sha256** [comment]
Command aliases in the bukkit command yml are not supported due to how areashop register commands.
