### ISSUE TITLE
Is there for version 1.20.4?

### ISSUE THREAD

**Issue by AresLykos** [md5sha256/AreaShop#34]
**Current behavior**
I've probably tried many versions, but I haven't come across a version that works on version 1.20.4. Is there one for version 1.20.4?
If so, how can I install it?

* Server platform (Bukkit, Spigot, etc.): spigot
* Server version: 1.20.4
* AreaShop version: 
* WorldEdit version: 7.3.0 (If I need to change it, I will change it.)
* WorldGuard version: 7.0.9 (If I need to change it, I will change it.)
* Vault version: 1.7.3

**Comment by md5sha256** [comment]
2.8.0 should support 1.20.4

**Comment by AresLykos** [comment]
ty :)
