### ISSUE TITLE
/as unrent FAWE crashes server, breaks bootup and duplicates money.

### ISSUE THREAD

**Issue by TomLewis** [md5sha256/AreaShop#6]
**Current behavior**
With FAWE 2.0.1 when a player uses `/as unrent` it crashes the server, this is a snippet of about 100 occurrences. 
https://gist.github.com/TomLewis/b89c644c77dba52dc32b04e5247b88a2

Which in turn restarts the server, and it also breaks boot startup!
https://gist.github.com/TomLewis/f4658c4a9cb7fff788b2caf06096340a

It also paid the user the FULL amount of money for unrenting even tho its suppose to be a percent, so there's 2 issues here too:
1) Its not paying a percentage back
2) the payment back is happening before the regions been restored/unrented. 

Another issue I saw is that you havent updated the /ver areashop
I have 2.7.3 jar on the server but /ver areashop shows 2.7.2

I backdatedto normal WorldEdit and it resolved the bootup issue.

**Your environment**
* Server version: PurPur 1.18.1 1506
* AreaShop version: 2.7.3
* WorldEdit version: FastAsyncWorldEdit-Bukkit-2.0.1-SNAPSHOT-68
* WorldGuard version: 7.0.6
* Vault version: 1.7.3

**Comment by md5sha256** [comment]
Fixed in 2.7.5
