### ISSUE TITLE
Problem with use

### ISSUE THREAD

**Issue by MsKiller01** [md5sha256/AreaShop#7]
**Current behavior**
Been offgrid since NLThijs left the scene and incompatibility forced us to take this plugin down, finding your fork, it works as far as possible, but there are some things I don't understand:
Renting an area, kinda works, sometimes the OP has to go in and look at the specs from AS and WG.
The player rents an area and according to WG it can not do anything inside that area, what is going on here? Should AS not give permission to the rentee to construct what the player wants, and after that the restore functions resets everything? 
Even if clicking on the sign to rent and then click to unrent, the area is restored to a previous build, not the beautiful nice work that was done aparently afterwards. The OP tried to change it in WG, by redefine the area, but that does not seem to work. Making the restore function to ' false'  does not undo the rentee has done so, what is the right action here....

**Desired behavior**
Renting an area should give total permission to do everything within the given(rented or bought) area, it does not.
Simpler instructions needed to alter a 'to rent' and/or 'to buy' area to change so that restore does not revert to only the first makup.

**Your environment**

* Server platform (Bukkit, Spigot, etc.):  
* Server version: [13:36:56 INFO]: Checking version, please wait...
[13:36:56 INFO]: This server is running Paper version git-Paper-175 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 9490475)
You are running the latest version
Previous version: git-Paper-170 (MC: 1.18.1)
* AreaShop version: [13:38:00 INFO]: AreaShop version 2.7.4
[13:38:00 INFO]: Selling and renting WorldGuard regions to your players, highly configurable.
[13:38:00 INFO]: Website: https://github.com/md5s256/AreaShop
[13:38:00 INFO]: Author: NLThijs48
* WorldEdit version: [13:38:54 INFO]: WorldEdit version 7.2.9-SNAPSHOT+6034-92dfe5e
* WorldGuard version: [13:39:18 INFO]: WorldGuard version 7.0.6+1cff55f
* Vault version: [13:39:50 INFO]: Vault version 1.7.3-b131
[13:39:50 INFO]: Vault is a Permissions & Economy API to allow plugins to more easily hook into these systems without needing to hook each individual system themselves.
[13:39:50 INFO]: Website: https://dev.bukkit.org/projects/vault
[13:39:50 INFO]: Authors: cereal, Sleaker and mung3r

**Your config files**

[AS-WG.zip](https://github.com/md5sha256/AreaShop/files/7925600/AS-WG.zip)

**Comment by MsKiller01** [comment]
It would be also nice if a command could be given for a whole lot of area's so that for example the restore function is changed from on to off without altering 300 files (takes a lot of time)
It would also be nice if it was possible to ' update' an area like I change a thing in an 'to rent' or 'to buy' area by simply /as update [name of area]

**Comment by MsKiller01** [comment]
We use also preciousstones plugin, this plugin does not need WG, so, my biggest Q here is, why can AS not work properly without WG?
I noticed the problem with WG trying to play boss on several occasions, especially when it concerns overlapping areas. So, talking to the devs of WG, actually one in particulary, made my complaint go away (simply unanswered deleting it), even going to that awful discord, he(this #%&^@) kicked me and others several times from Discord. So I am NOT going to have a conversation with childish people who can't take an argument serious, that said, I wish there was a way to use Areashop without having the use/need of Worldguard . Because of one rotten apple in the basket.......

**Comment by md5sha256** [comment]
Yes, that particular person you are referring to is known to be like that. Anyway, AreaShop is bound to WG in a way which is difficult to uncouple. The whole concept of AreaShop is to sell WG regions and not just any protected region in general.

**Comment by md5sha256** [comment]
> Even if clicking on the sign to rent and then click to unrent, the area is restored to a previous build, not the beautiful nice work that was done aparently afterwards. The OP tried to change it in WG, by redefine the area, but that does not seem to work. Making the restore function to ' false' does not undo the rentee has done so, what is the right action here....

This is intended behaviour. Setting the restore function to `false` will stop the region from being restored *in the future*.

**Comment by md5sha256** [comment]
> It would be also nice if a command could be given for a whole lot of area's so that for example the restore function is changed from on to off without altering 300 files (takes a lot of time) It would also be nice if it was possible to ' update' an area like I change a thing in an 'to rent' or 'to buy' area by simply /as update [name of area]

Yes, such a feature already exists, that's what region groups are for.

**Comment by MsKiller01** [comment]
> Yes, that particular person you are referring to is known to be like that
Thank you for such a nice confirmation about that ' guy'  I thought I was going mad here.... (for a very brief second)

**Comment by MsKiller01** [comment]
> Yes, that particular person you are referring to is known to be like that. Anyway, AreaShop is bound to WG in a way which is difficult to uncouple. The whole concept of AreaShop is to sell WG regions and not just any protected region in general.

Thank you for such a nice confirmation about that ' guy'  I thought I was going mad here.... (for a very brief second) If this was one of my staff? He would have to find another job.... but that's me... and I was only asking in general there a nice formed question.... how rude! Anyway, not going there if needed.

**Comment by MsKiller01** [comment]
> Yes, such a feature already exists, that's what region groups are for.

Can you please tell me how I accomplish this? the videos I watched did not reveal a thing, and they are a bit outdated....
Thanks for your help and I hope that you are able to keep Areashop alive!

**Comment by md5sha256** [comment]
> Can you please tell me how I accomplish this? the videos I watched did not reveal a thing, and they are a bit outdated....
Thanks for your help and I hope that you are able to keep Areashop alive!

I'm not entirely sure myself as I haven't used them personally. Best guess is there's a yaml file and you add regions to the specific group. The group's setting values (as you would a normal regionName.yml) should override the region's settings.

**Comment by MsKiller01** [comment]
A shame, so I think I'm gonna have to look into it by myself then... Anyway, thanks for keeping this alive....
