### ISSUE TITLE
Make notice of update redirect path

### ISSUE THREAD

**Issue by MsKiller01** [md5sha256/AreaShop#8]
**Describe the problem you are trying to solve with this feature request**

I got a message from the plugin saying that I needed to update Areashop v.2.7.5 snapshot to v.2.7.5, I would like to, but on github there is only the snapshot version, and the message tells us to go to NLThijs'  Spigot page, and as I do remember you telling me that is not your goal to put the plugin on.

**Describe the solution you'd like**

Maybe a message from the plugin to a direct link on github then?

That's all. Thanks...

**Comment by md5sha256** [comment]
Fixed in 2.7.8
