### ISSUE TITLE
schematic creation fails

### ISSUE THREAD

**Issue by EvilOlaf** [md5sha256/AreaShop#9]
Hey there,

**Current behavior**
```
[10:03:26 INFO]: Olaf issued server command: /as add rent shop2
[10:03:26 WARN]: [FastAsyncWorldEdit] Plugin FastAsyncWorldEdit v2.0.2-SNAPSHOT-116;fb66ba6 generated an exception while executing task 4957
com.fastasyncworldedit.core.internal.exception.FaweException: Too many block checks
```

**Expected behavior**
It should create the schematic I guess.

**Steps to reproduce**

1. `enableRestore: true`
2. start server
3. Create a WorldGuard region
4. try adding it as rented
5. check console for error

**Your environment**

* Server platform (Bukkit, Spigot, etc.):  Paper
* Server version: Paper snapshot 235, implementing 1.18.2
* AreaShop version: dev/bleeding including https://github.com/md5sha256/AreaShop/commit/e64e884c2aabd50e630c4dbbae119fb4e277293e
* WorldEdit version: FAWE snapshot 116
* WorldGuard version:  snapshot 2185
* Vault version: https://github.com/danielk42/Vault

**Your config files**
Unchanged except  `enableRestore: true` in default.yml

Cheers

**Comment by md5sha256** [comment]
Fixed in 2.7.8
